ktor:
  development: "$DEV:false"
  application:
    modules:
      - org.ksystem.app.MainKt.module
  deployment:
    port: "$PORT:8080"

app:
  server:
    frontendHost: "$FRONTEND_HOST"
  database:
    url: "$DATABASE_URL"
    user: "$DATABASE_USER"
    password: "$DATABASE_PASSWORD"
    poolSize: "$POOL_SIZE:6"
  token:
    secret: "$JWT_SECRET"
    issuer: "$JWT_ISSUER"
    audience: "$JWT_AUDIENCE"
    ttl: "$JWT_TTL:3600000"
